apiVersion: v1
kind: PersistentVolume
metadata:
  name: persist-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: persist
  nfs:
    # FIXME: use the right IP
    server: <IP-nuc03>
    path: "/var/nfs/persist"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persist-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: persist
  resources:
    requests:
        storage: 500Gi